// YOU HAVE TO WRITE TWO STRUCTS
// STRUCT ORDER .. id price qty buy/sell
// STRUCT Trader ... id name

//  IN ONE CODE U HAVE TO ONLY WRITE STACK BASED STUFF
// YOU HAVE TO PROMISE U DONT USE ANY  HEAP MEMORY

// 5 TRADERS IN A FOR LOOP
// EACX SECOND THEY SEND 100 ORDERS


STRACE

// HEAP VERSION OF IT
